[package]
name = "nineties"
version = "0.0.4"
edition = "2021"
authors = ["Savio Resende <savio@savioresende.com>"]
description = "An app starter for traditional web apps."
license = "MIT"
repository = "https://github.com/lotharthesavior/nineties"

[dependencies]
include_dir = "0.6"